### ISSUE TITLE
open_cachefile not creating and opening file as read-write when file does not exist

### ISSUE THREAD

**Issue by t0astt** [komand/plugin-sdk-python#16]
Just as the title states. When attempting to open a cache file that does not exist and it is created, the cache file is opened in write mode, not read. 

Error from Python:` IOError: File not open for reading`

**Comment by jonschipp** [comment]
Fixed in https://github.com/komand/plugin-sdk-python/commit/0657ddd46be6e50b6fc9d4009bebe912be4e511d
