### ISSUE TITLE
Generated <plugin>-run script is generated with typo

### ISSUE THREAD

**Issue by t0astt** [komand/plugin-sdk-python#23]
The <plugin>-run script that is generated by `make` is being generated with a typo that prevents it from running. The contents look like the following:

`#!/bin/sh\ndocker run --rm -i komand/malwareconfig:0.1.0 $@`

Corrected, it would be: 
`#!/bin/sh`
`docker run --rm -i komand/malwareconfig:0.1.0 $@`

**Comment by jonschipp** [comment]
Thanks for reporting. Let me make sure that gets rendered correctly
