### ISSUE TITLE
Import error with SDK 0.3

### ISSUE THREAD

**Issue by t0astt** [komand/plugin-sdk-python#29]
My Python plugin SDK version was updated to 0.3. Before the update my module import was successful. After the update, running the plugin led to the following error: `python ImportError: No module named ...`. 

Reverting `FROM komand/python-plugin:0.2` in the Dockerfile and running `make` again fixed the issue.

**Comment by StabbyCutyou** [comment]
Is this still an issue?

**Comment by jandre** [comment]
What exactly is the import statement?

The problem is that 0.3 uses Python 3, which changes how you can import things.  certain statements in Python 2 are not valid
