### ISSUE TITLE
Clean_dict should support nested dicts

### ISSUE THREAD

**Issue by jonschipp** [komand/plugin-sdk-python#37]
the `clean_dict` function should support removing keys with `NoneType` or empty strings from nested dictionaries. Currently, it won't work for nested dicts:
```
{ 'domain_record': {'type': 'TXT', 'data': 'qwerty', 'id': 22743347, 'port': None, 'weight': None, 'priority': None, 'name': 'cats'}}
```

**Comment by jonschipp** [comment]
Jen provided this, we need to test it
```
def clean_dict_recursive(obj):
    obj = komand.helper.clean_dict(obj)
    for k, v in obj.items():
        if isinstance(v, dict):
            obj[k] = clean_dict_recursive(v)

    return  obj
```

**Comment by t0astt** [comment]
Tested in an action I was working on. Everything went OK.

**Comment by t0astt** [comment]
I think we can close this issue now that we have the universal `clean` function implemented in the helper library.
