### ISSUE TITLE
Connections from plugins to localhost are refused

### ISSUE THREAD

**Issue by nathanielltaylor** [komand/plugin-sdk-python#43]
HTTP requests made with the Requests library to localhost addresses are actively refused. This has been tested with instances of Cuckoo Sandbox, PrestoDB, and MISP. Identical HTTP requests passed from a browser, Postman, via curl, and by a standalone Python script succeed.

Current workaround is to host the instance of the product required in a VM. Plugins can contact Cuckoo normally when it is hosted in a `docker-machine` Docker container.

**Comment by jonschipp** [comment]
This is because localhost in the container is not localhost on the host and I don't think localhost in the container is localhost in the VM by default they're not shared.
